### ISSUE TITLE
Shoutbox doesnt show and acp link doesnt work

### ISSUE THREAD

**Issue by Keziolio** [Schamper/nodebb-plugin-shoutbox#70]
Installing the plugin has no effect, and when i go in the admin control panel in the "installed plugins" tab and i click the "shoutbox" button it gives me a 404 error

Using nodebb 0.6.0, already reloaded & restarted

**Comment by Keziolio** [comment]
```log
5/1 09:55 [26699] - error: TypeError: Cannot call method 'render' of undefined
    at Object.Shoutbox.settings.addUserSettings [as method] (/home/oculuszone/forum/nodebb/node_modules/nodebb-plugin-shoutbox/library.js:97:7)
    at /home/oculuszone/forum/nodebb/src/plugins.js:423:12
    at /home/oculuszone/forum/nodebb/node_modules/async/lib/async.js:272:13
    at iterate (/home/oculuszone/forum/nodebb/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/oculuszone/forum/nodebb/node_modules/async/lib/async.js:165:9)
    at Object.async.reduce (/home/oculuszone/forum/nodebb/node_modules/async/lib/async.js:271:15)
    at fireFilterHook (/home/oculuszone/forum/nodebb/src/plugins.js:415:9)
    at Object.Plugins.fireHook (/home/oculuszone/forum/nodebb/src/plugins.js:400:5)
    at Object.async.parallel.settings (/home/oculuszone/forum/nodebb/src/controllers/accounts.js:367:13)
    at /home/oculuszone/forum/nodebb/node_modules/async/lib/async.js:583:25
[cluster] Child Process (26699) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

**Comment by tedr56** [comment]
The shoutbox is not compatible with NodeBB 0.6.0 at the moment

**Comment by Keziolio** [comment]
Ok, any chances it will be soon?

Thanks.

**Comment by Schamper** [comment]
Soon :+1:

**Comment by Schamper** [comment]
I've actually started on this and also started refactoring a great deal. Server part is mostly done and 0.6.x compatible. Client part will soon follow with just compatibility at first and improvements down the line.

**Comment by tedr56** [comment]
That's great news! :+1:
